version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Create RPi raw image with data partition
          command: |
            make rpi-raw-image-data

      - run:
          name: Create RPi raw image
          command: |
            make rpi-raw-image

      - run:
          name: Create Odroid raw image
          command: |
            make odroid-raw-image

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp *raw* output/

      - store_artifacts:
          path: /home/circleci/project/output

  deploy:
    machine: true
    steps:
      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              curl -sSL https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz -o ghr.tar.gz
              tar xzf ghr.tar.gz
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ./ghr_v0.13.0_linux_amd64/ghr $pre -u rpi-cluster $CIRCLE_TAG output/
            fi

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/